# Generated by Django 5.0.3 on 2024-04-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=False, max_length=1000000),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default=False, max_length=1000000),
        ),
    ]
